import { 
  Tenant, 
  User, 
  WhatsAppInstance, 
  Contact, 
  Pipeline, 
  Deal, 
  Conversation, 
  Message, 
  AIInsight, 
  Task, 
  SLAAlert, 
  Campaign, 
  QuickReplyTemplate 
} from '@/types/crm';

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 'tenant-vanguard-01',
    name: 'Vanguard Prime Imóveis',
    slug: 'vanguard-prime',
    documentCnpj: '34.567.890/0001-12',
    logoUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=128&auto=format&fit=crop&q=60',
    primaryColor: '#059669',
    timezone: 'America/Sao_Paulo',
    businessHours: {
      start: '08:30',
      end: '19:00',
      workDays: [1, 2, 3, 4, 5, 6],
    },
    settings: {
      slaFirstResponseMinutes: 15,
      slaInactivityHours: 24,
      autoAssignRule: 'ROUND_ROBIN',
      aiCopilotEnabled: true,
      requireHumanApprovalForAI: true,
    }
  },
  {
    id: 'tenant-horizonte-02',
    name: 'Horizonte Empreendimentos',
    slug: 'horizonte-imoveis',
    documentCnpj: '12.345.678/0001-90',
    logoUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=128&auto=format&fit=crop&q=60',
    primaryColor: '#0284c7',
    timezone: 'America/Sao_Paulo',
    businessHours: {
      start: '09:00',
      end: '18:30',
      workDays: [1, 2, 3, 4, 5],
    },
    settings: {
      slaFirstResponseMinutes: 20,
      slaInactivityHours: 48,
      autoAssignRule: 'UNASSIGNED_QUEUE',
      aiCopilotEnabled: true,
      requireHumanApprovalForAI: true,
    }
  }
];

export const MOCK_USERS: User[] = [
  {
    id: 'user-rafael-admin',
    name: 'Rafael Sena',
    email: 'rafael@vanguardprime.com.br',
    phone: '+55 11 98877-6655',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'ADMIN',
    isActive: true,
  },
  {
    id: 'user-camila-gestora',
    name: 'Camila Mendonça',
    email: 'camila@vanguardprime.com.br',
    phone: '+55 11 97766-5544',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'MANAGER',
    isActive: true,
  },
  {
    id: 'user-lucas-corretor',
    name: 'Lucas Brandão',
    email: 'lucas@vanguardprime.com.br',
    phone: '+55 11 96655-4433',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'BROKER',
    isActive: true,
  },
  {
    id: 'user-juliana-corretora',
    name: 'Juliana Paes Costa',
    email: 'juliana@vanguardprime.com.br',
    phone: '+55 11 95544-3322',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'BROKER',
    isActive: true,
  }
];

export const MOCK_INSTANCES: WhatsAppInstance[] = [
  {
    id: 'inst-01',
    tenantId: 'tenant-vanguard-01',
    name: 'WhatsApp Principal - Vendas Jardins',
    phoneNumber: '+55 (11) 99876-5432',
    zapiInstanceId: '3C9B8A7F20D1',
    status: 'CONNECTED',
    batteryLevel: 94,
    lastSyncAt: new Date().toISOString(),
  },
  {
    id: 'inst-02',
    tenantId: 'tenant-vanguard-01',
    name: 'Plantão Lançamentos Faria Lima',
    phoneNumber: '+55 (11) 98765-4321',
    zapiInstanceId: '7E4A1B998C32',
    status: 'CONNECTED',
    batteryLevel: 88,
    lastSyncAt: new Date().toISOString(),
  }
];

export const MOCK_PIPELINES: Pipeline[] = [
  {
    id: 'pipe-vendas-residencial',
    tenantId: 'tenant-vanguard-01',
    name: 'Vendas Residencial Alto Padrão',
    isDefault: true,
    stages: [
      { id: 'stage-1', pipelineId: 'pipe-vendas-residencial', name: '1. Novo Lead WhatsApp', order: 1, slaHours: 2, colorHex: '#3b82f6' },
      { id: 'stage-2', pipelineId: 'pipe-vendas-residencial', name: '2. Primeiro Contato Realizado', order: 2, slaHours: 12, colorHex: '#6366f1' },
      { id: 'stage-3', pipelineId: 'pipe-vendas-residencial', name: '3. Em Qualificação / Perfil', order: 3, slaHours: 24, colorHex: '#8b5cf6' },
      { id: 'stage-4', pipelineId: 'pipe-vendas-residencial', name: '4. Imóveis Apresentados', order: 4, slaHours: 48, colorHex: '#a855f7' },
      { id: 'stage-5', pipelineId: 'pipe-vendas-residencial', name: '5. Visita Agendada', order: 5, slaHours: 72, colorHex: '#d97706' },
      { id: 'stage-6', pipelineId: 'pipe-vendas-residencial', name: '6. Proposta em Mesa', order: 6, slaHours: 48, colorHex: '#f59e0b' },
      { id: 'stage-7', pipelineId: 'pipe-vendas-residencial', name: '7. Análise de Crédito', order: 7, slaHours: 96, colorHex: '#10b981' },
      { id: 'stage-8', pipelineId: 'pipe-vendas-residencial', name: '8. Contrato Fechado', order: 8, slaHours: 0, colorHex: '#059669', isWon: true },
      { id: 'stage-9', pipelineId: 'pipe-vendas-residencial', name: 'Perdido / Descarte', order: 9, slaHours: 0, colorHex: '#ef4444', isLost: true },
    ]
  }
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'contact-01',
    tenantId: 'tenant-vanguard-01',
    name: 'Dr. Roberto Silveira',
    phone: '+5511991234567',
    email: 'dr.roberto.silveira@hospital.med.br',
    cpf: '123.***.***-89',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    monthlyIncome: 65000,
    householdIncome: 90000,
    downPaymentAvailable: 800000,
    estimatedFinancing: 1800000,
    minPropertyValue: 2200000,
    maxPropertyValue: 3000000,
    preferredPropertyType: 'PENTHOUSE',
    purchasePurpose: 'LIVING',
    targetRegions: ['Jardins', 'Itaim Bibi', 'Vila Nova Conceição'],
    targetBedrooms: 3,
    targetParkingSpots: 3,
    purchaseTimeline: '1_TO_3_MONTHS',
    source: 'WHATSAPP',
    temperature: 'HOT',
    aiPriorityScore: 94,
    assignedUserId: 'user-lucas-corretor',
    tags: ['Alto Padrão', 'Médico', 'Entrada Alta', 'Visita no Sábado'],
    notesCount: 4,
    consentGiven: true,
    consentDate: '2026-08-10T14:30:00Z',
    hasOptedOut: false,
    lastClientInteractionAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    lastTeamInteractionAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    createdAt: '2026-08-10T14:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'contact-02',
    tenantId: 'tenant-vanguard-01',
    name: 'Fernanda Castanheira',
    phone: '+5511987654321',
    email: 'fernanda.castanheira@techcorp.io',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    monthlyIncome: 38000,
    householdIncome: 55000,
    downPaymentAvailable: 400000,
    minPropertyValue: 1200000,
    maxPropertyValue: 1600000,
    preferredPropertyType: 'APARTMENT',
    purchasePurpose: 'LIVING',
    targetRegions: ['Pinheiros', 'Vila Madalena'],
    targetBedrooms: 2,
    targetParkingSpots: 2,
    purchaseTimeline: 'IMMEDIATE',
    source: 'INSTAGRAM_ADS',
    temperature: 'HOT',
    aiPriorityScore: 89,
    assignedUserId: 'user-juliana-corretora',
    tags: ['Lançamento Pinheiros', 'Aceita Financiamento', 'Pet Friendly'],
    notesCount: 2,
    consentGiven: true,
    hasOptedOut: false,
    lastClientInteractionAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    lastTeamInteractionAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    createdAt: '2026-08-12T10:15:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'contact-03',
    tenantId: 'tenant-vanguard-01',
    name: 'Carlos Eduardo Nogueira',
    phone: '+5511977778888',
    email: 'carlos.edu@investimentos.com',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    monthlyIncome: 45000,
    downPaymentAvailable: 1500000,
    minPropertyValue: 800000,
    maxPropertyValue: 1800000,
    preferredPropertyType: 'STUDIO',
    purchasePurpose: 'INVESTMENT',
    targetRegions: ['Faria Lima', 'Bela Vista', 'Consolação'],
    purchaseTimeline: 'INVESTOR_OPPORTUNITY',
    source: 'PORTAL_ZAP',
    temperature: 'WARM',
    aiPriorityScore: 78,
    assignedUserId: 'user-lucas-corretor',
    tags: ['Investidor', 'Short Stay / Airbnb', 'Pagamento à Vista'],
    notesCount: 1,
    consentGiven: true,
    hasOptedOut: false,
    lastClientInteractionAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    lastTeamInteractionAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'contact-04',
    tenantId: 'tenant-vanguard-01',
    name: 'Mariana Guimarães',
    phone: '+5511966551122',
    email: 'mari.guimaraes@arq.br',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    monthlyIncome: 28000,
    downPaymentAvailable: 250000,
    minPropertyValue: 950000,
    maxPropertyValue: 1200000,
    preferredPropertyType: 'APARTMENT',
    purchasePurpose: 'LIVING',
    targetRegions: ['Moema', 'Campo Belo'],
    targetBedrooms: 2,
    targetParkingSpots: 1,
    purchaseTimeline: '3_TO_6_MONTHS',
    source: 'FACEBOOK_ADS',
    temperature: 'COLD',
    aiPriorityScore: 52,
    assignedUserId: undefined, // Sem corretor
    tags: ['Aguardando Atribuição', 'Sem Resposta'],
    notesCount: 0,
    consentGiven: true,
    hasOptedOut: false,
    lastClientInteractionAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'deal-01',
    tenantId: 'tenant-vanguard-01',
    contactId: 'contact-01',
    pipelineId: 'pipe-vendas-residencial',
    stageId: 'stage-5', // Visita Agendada
    assignedUserId: 'user-lucas-corretor',
    title: 'Cobertura Duplex 280m² - Horizon Jardins',
    expectedValue: 2850000,
    manualProbability: 80,
    aiProbabilityScore: 88,
    status: 'OPEN',
    propertyInterest: 'Horizon Jardins - Apto 242 (R$ 2.85M)',
    createdAt: '2026-08-10T15:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-02',
    tenantId: 'tenant-vanguard-01',
    contactId: 'contact-02',
    pipelineId: 'pipe-vendas-residencial',
    stageId: 'stage-4', // Imóveis Apresentados
    assignedUserId: 'user-juliana-corretora',
    title: 'Apto 88m² 2 Suítes - Icon Pinheiros',
    expectedValue: 1420000,
    manualProbability: 70,
    aiProbabilityScore: 82,
    status: 'OPEN',
    propertyInterest: 'Icon Pinheiros - Unidade 114 (R$ 1.42M)',
    createdAt: '2026-08-12T11:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'deal-03',
    tenantId: 'tenant-vanguard-01',
    contactId: 'contact-03',
    pipelineId: 'pipe-vendas-residencial',
    stageId: 'stage-6', // Proposta em Mesa
    assignedUserId: 'user-lucas-corretor',
    title: '2x Studios 32m² Mobiliados - Hub Faria Lima',
    expectedValue: 1280000,
    manualProbability: 85,
    aiProbabilityScore: 91,
    status: 'OPEN',
    propertyInterest: 'Hub Faria Lima - Studios 702 e 703',
    createdAt: '2026-08-15T09:30:00Z',
    updatedAt: new Date().toISOString(),
  }
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-01',
    tenantId: 'tenant-vanguard-01',
    instanceId: 'inst-01',
    contactId: 'contact-01',
    assignedUserId: 'user-lucas-corretor',
    status: 'PENDING_TEAM',
    lastMessagePreview: 'Combinado Lucas! Podemos agendar a visita no sábado às 10h da manhã?',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    unreadCount: 1,
    slaBreached: true,
    slaBreachReason: 'Aguardando resposta da equipe há mais de 20 minutos',
  },
  {
    id: 'conv-02',
    tenantId: 'tenant-vanguard-01',
    instanceId: 'inst-01',
    contactId: 'contact-02',
    assignedUserId: 'user-juliana-corretora',
    status: 'OPEN',
    lastMessagePreview: 'Adorei a planta do Icon Pinheiros! O condomínio aceita pets grandes?',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    unreadCount: 2,
    slaBreached: false,
  },
  {
    id: 'conv-03',
    tenantId: 'tenant-vanguard-01',
    instanceId: 'inst-01',
    contactId: 'contact-03',
    assignedUserId: 'user-lucas-corretor',
    status: 'PENDING_CLIENT',
    lastMessagePreview: 'Enviei a simulação de yield com base em locação por temporada. Fico no aguardo!',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    unreadCount: 0,
    slaBreached: false,
  },
  {
    id: 'conv-04',
    tenantId: 'tenant-vanguard-01',
    instanceId: 'inst-02',
    contactId: 'contact-04',
    assignedUserId: undefined,
    status: 'UNASSIGNED',
    lastMessagePreview: 'Olá, vi o anúncio no Facebook sobre os apartamentos em Moema.',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    unreadCount: 1,
    slaBreached: true,
    slaBreachReason: 'Lead novo sem primeiro atendimento há 3 horas',
  }
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-01',
    tenantId: 'tenant-vanguard-01',
    conversationId: 'conv-01',
    externalId: 'zapi-msg-1001',
    senderType: 'CONTACT',
    messageType: 'TEXT',
    content: 'Olá! Sou o Dr. Roberto. Vi o anúncio da cobertura no Horizon Jardins no WhatsApp. Ainda está disponível?',
    status: 'READ',
    isInternalNote: false,
    timestamp: '2026-08-10T14:30:00Z',
  },
  {
    id: 'msg-02',
    tenantId: 'tenant-vanguard-01',
    conversationId: 'conv-01',
    senderType: 'USER',
    senderUserId: 'user-lucas-corretor',
    senderName: 'Lucas Brandão',
    messageType: 'TEXT',
    content: 'Boa tarde Dr. Roberto! Prazer falar com o senhor. Sim, a cobertura duplex de 280m² com vista panorâmica para o Jardins está disponível. O imóvel conta com 3 suítes plenas e 3 vagas livres.',
    status: 'READ',
    isInternalNote: false,
    timestamp: '2026-08-10T14:38:00Z',
  },
  {
    id: 'msg-03',
    tenantId: 'tenant-vanguard-01',
    conversationId: 'conv-01',
    senderType: 'USER',
    senderUserId: 'user-lucas-corretor',
    senderName: 'Lucas Brandão',
    messageType: 'TEXT',
    content: 'Cliente tem renda médica comprovada e busca moradia definitiva para a família. Prioriza privacidade e segurança 24h.',
    status: 'SENT',
    isInternalNote: true, // NOTA PRIVADA
    timestamp: '2026-08-10T14:45:00Z',
  },
  {
    id: 'msg-04',
    tenantId: 'tenant-vanguard-01',
    conversationId: 'conv-01',
    externalId: 'zapi-msg-1004',
    senderType: 'CONTACT',
    messageType: 'TEXT',
    content: 'Perfeito. Tenho cerca de R$ 800 mil de entrada disponível e o restante farei financiamento bancário pelo Santander. Qual seria o valor de condomínio e IPTU?',
    status: 'READ',
    isInternalNote: false,
    timestamp: '2026-08-10T15:10:00Z',
  },
  {
    id: 'msg-05',
    tenantId: 'tenant-vanguard-01',
    conversationId: 'conv-01',
    senderType: 'USER',
    senderUserId: 'user-lucas-corretor',
    senderName: 'Lucas Brandão',
    messageType: 'TEXT',
    content: 'Excelente, doutor! O condomínio é R$ 2.450/mês e o IPTU R$ 980/mês. Já preparei um caderno digital com fotos reais e o tour 3D.',
    status: 'READ',
    isInternalNote: false,
    timestamp: '2026-08-10T15:20:00Z',
  },
  {
    id: 'msg-06',
    tenantId: 'tenant-vanguard-01',
    conversationId: 'conv-01',
    externalId: 'zapi-msg-1006',
    senderType: 'CONTACT',
    messageType: 'TEXT',
    content: 'Combinado Lucas! Podemos agendar a visita no sábado às 10h da manhã?',
    status: 'READ',
    isInternalNote: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  }
];

export const MOCK_AI_INSIGHTS: Record<string, AIInsight> = {
  'conv-01': {
    id: 'ai-ins-01',
    tenantId: 'tenant-vanguard-01',
    conversationId: 'conv-01',
    contactId: 'contact-01',
    summary: 'Dr. Roberto Silveira (médico, alta renda) está altamente qualificado para a cobertura Horizon Jardins (R$ 2.85M). Informou entrada de R$ 800k e financiamento pelo Santander. Solicitou visita formal para este sábado às 10h.',
    extractedData: {
      monthlyIncome: 65000,
      downPayment: 800000,
      maxBudget: 3000000,
      preferredRegion: 'Jardins / Vila Nova Conceição',
      propertyType: 'PENTHOUSE / COBERTURA',
      urgencyLevel: 'ALTA',
      detectedObjections: ['Confirmar custos de condomínio e vaga de garagem para SUV'],
    },
    sentiment: 'POSITIVE',
    intent: 'AGENDAR_VISITA',
    suggestedResponse: 'Perfeito, Dr. Roberto! Agendado para este sábado às 10h no Residencial Horizon Jardins (Rua Oscar Freire, 1400). Enviarei a autorização de entrada na portaria em seu nome. O senhor prefere que eu o receba no lobby?',
    confidenceScore: 96,
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  'conv-02': {
    id: 'ai-ins-02',
    tenantId: 'tenant-vanguard-01',
    conversationId: 'conv-02',
    contactId: 'contact-02',
    summary: 'Fernanda demonstrou forte interesse no Icon Pinheiros (2 suítes). Dúvida pontual sobre política pet do condomínio para cães de grande porte.',
    extractedData: {
      monthlyIncome: 38000,
      downPayment: 400000,
      maxBudget: 1600000,
      preferredRegion: 'Pinheiros',
      propertyType: 'APARTAMENTO',
      urgencyLevel: 'ALTA',
      detectedObjections: ['Política de pets grandes na convenção do condomínio'],
    },
    sentiment: 'POSITIVE',
    intent: 'DUVIDA_GERAL',
    suggestedResponse: 'Olá Fernanda! Sim, o Icon Pinheiros é 100% pet-friendly e inclusive conta com um Pet Place completo e área verde dedicada. Qual a raça do seu companheiro?',
    confidenceScore: 92,
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  }
};

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-01',
    tenantId: 'tenant-vanguard-01',
    contactId: 'contact-01',
    dealId: 'deal-01',
    assignedUserId: 'user-lucas-corretor',
    title: 'Visita Presencial Cobertura Horizon Jardins com Dr. Roberto',
    description: 'Confirmar liberação na portaria com o síndico e levar kit boas-vindas Vanguard.',
    taskType: 'VISIT',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    priority: 'HIGH',
    isCompleted: false,
  },
  {
    id: 'task-02',
    tenantId: 'tenant-vanguard-01',
    contactId: 'contact-02',
    dealId: 'deal-02',
    assignedUserId: 'user-juliana-corretora',
    title: 'Enviar Convenção de Condomínio e Fotos do Pet Place para Fernanda',
    taskType: 'WHATSAPP',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(),
    priority: 'MEDIUM',
    isCompleted: false,
  },
  {
    id: 'task-03',
    tenantId: 'tenant-vanguard-01',
    contactId: 'contact-03',
    dealId: 'deal-03',
    assignedUserId: 'user-lucas-corretor',
    title: 'Acompanhar aprovação da minuta de proposta com Carlos Eduardo',
    taskType: 'PROPOSAL',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    priority: 'HIGH',
    isCompleted: false,
  }
];

export const MOCK_ALERTS: SLAAlert[] = [
  {
    id: 'alert-01',
    tenantId: 'tenant-vanguard-01',
    type: 'FIRST_RESPONSE_OVERDUE',
    severity: 'CRITICAL',
    title: 'Lead novo sem atendimento há 3 horas',
    description: 'Mariana Guimarães enviou mensagem via WhatsApp de campanha Facebook e ainda não foi atribuída.',
    contactId: 'contact-04',
    conversationId: 'conv-04',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    isDismissed: false,
  },
  {
    id: 'alert-02',
    tenantId: 'tenant-vanguard-01',
    type: 'STAGE_SLA_EXCEEDED',
    severity: 'WARNING',
    title: 'SLA de Resposta Excedido',
    description: 'Dr. Roberto Silveira aguarda resposta de agendamento há mais de 25 minutos.',
    contactId: 'contact-01',
    conversationId: 'conv-01',
    assignedUserId: 'user-lucas-corretor',
    createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    isDismissed: false,
  }
];

export const MOCK_QUICK_REPLIES: QuickReplyTemplate[] = [
  {
    id: 'qr-01',
    tenantId: 'tenant-vanguard-01',
    shortcut: '/apresentacao',
    title: 'Apresentação Institucional & Corretor',
    category: 'GREETING',
    content: 'Olá! Sou {{corretor_nome}}, consultor especialista da Vanguard Prime Imóveis. É um prazer atender você! Como posso te ajudar na busca do seu imóvel ideal hoje?',
  },
  {
    id: 'qr-02',
    tenantId: 'tenant-vanguard-01',
    shortcut: '/qualificacao',
    title: 'Perguntas de Qualificação Financeira',
    category: 'QUALIFICATION',
    content: 'Para que eu selecione as melhores opções exclusivas para você: você tem preferência por alguma região específica e qual faixa de investimento ou entrada você tem em mente?',
  },
  {
    id: 'qr-03',
    tenantId: 'tenant-vanguard-01',
    shortcut: '/visita',
    title: 'Convite para Visita VIP',
    category: 'VISIT',
    content: 'Temos a chave e autorização exclusiva para apresentar essa unidade decorada. O que acha de agendarmos uma visita VIP esta semana? Qual dia e horário ficam melhores para você?',
  },
  {
    id: 'qr-04',
    tenantId: 'tenant-vanguard-01',
    shortcut: '/simulacao',
    title: 'Simulação de Financiamento Caixa/Itaú/Santander',
    category: 'PROPERTIES',
    content: 'Trabalhamos com os principais bancos e conseguimos taxas especiais de financiamento. Se desejar, faço uma simulação personalizada da sua entrada e parcelas em poucos minutos!',
  }
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-01',
    tenantId: 'tenant-vanguard-01',
    name: 'Lançamento Pré-Venda: Residencial Horizon Jardins',
    instanceId: 'inst-01',
    targetSegment: 'Leads Quentes e Investidores (Orçamento > R$ 2M)',
    totalRecipients: 142,
    sentCount: 142,
    deliveredCount: 139,
    readCount: 118,
    repliedCount: 34,
    optOutCount: 1,
    status: 'COMPLETED',
    messageTemplate: 'Olá {{nome}}, oportunidade exclusiva antes do lançamento oficial: unidades decoradas do Horizon Jardins abertas para visitação restrita esta semana!',
    sendRatePerMinute: 20,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'camp-02',
    tenantId: 'tenant-vanguard-01',
    name: 'Reativação de Leads Inativos (Q2/2026)',
    instanceId: 'inst-02',
    targetSegment: 'Contatos sem interação há mais de 30 dias',
    totalRecipients: 85,
    sentCount: 42,
    deliveredCount: 41,
    readCount: 29,
    repliedCount: 8,
    optOutCount: 0,
    status: 'RUNNING',
    messageTemplate: 'Olá {{nome}}, tudo bem? Passando para te atualizar sobre 3 novas oportunidades com condições especiais na região que você estava buscando.',
    sendRatePerMinute: 15,
    createdAt: '2026-08-18T14:00:00Z',
  }
];

export const MOCK_AUTOMATIONS = [
  {
    id: 'auto-01',
    tenantId: 'tenant-vanguard-01',
    name: 'Boas-vindas Instantânea para Novos Leads do WhatsApp',
    description: 'Quando um lead novo entrar pela Z-API, atribui corretor via rodízio e agenda tarefa de 1º atendimento em 15 minutos.',
    triggerType: 'LEAD_CREATED',
    isActive: true,
    conditions: [
      { field: 'source', operator: 'EQUALS', value: 'WHATSAPP' }
    ],
    actions: [
      { actionType: 'ASSIGN_BROKER_ROUND_ROBIN', config: {} },
      { actionType: 'CREATE_TASK', config: { title: 'Primeiro Atendimento via WhatsApp', priority: 'HIGH', dueMinutes: 15 } },
      { actionType: 'ADD_TAG', config: { tag: 'WhatsApp-Inbound' } }
    ],
    executionCount: 148,
    lastExecutedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'auto-02',
    tenantId: 'tenant-vanguard-01',
    name: 'Lead Quente de Alta Renda -> Atribuição Gestor Sênior',
    description: 'Se o orçamento do imóvel for maior que R$ 2.500.000, aplica tag VIP e notifica a gestão comercial imediatamente.',
    triggerType: 'LEAD_CREATED',
    isActive: true,
    conditions: [
      { field: 'temperature', operator: 'EQUALS', value: 'HOT' }
    ],
    actions: [
      { actionType: 'ADD_TAG', config: { tag: 'Cliente-VIP' } },
      { actionType: 'NOTIFY_TEAM', config: { message: 'Novo lead VIP acima de R$ 2.5M cadastrado!' } }
    ],
    executionCount: 29,
    lastExecutedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    createdAt: '2026-08-05T14:00:00Z',
  },
  {
    id: 'auto-03',
    tenantId: 'tenant-vanguard-01',
    name: 'Alerta de Lead Inativo há mais de 48 Horas',
    description: 'Quando um lead ficar 48h sem resposta da equipe, dispara alerta crítico no dashboard.',
    triggerType: 'LEAD_INACTIVE',
    isActive: true,
    conditions: [],
    actions: [
      { actionType: 'CREATE_TASK', config: { title: 'Follow-up Urgente de Reativação', priority: 'HIGH', dueMinutes: 60 } }
    ],
    executionCount: 64,
    lastExecutedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    createdAt: '2026-08-08T09:00:00Z',
  }
];

export const MOCK_AUTOMATION_LOGS = [
  {
    id: 'log-01',
    tenantId: 'tenant-vanguard-01',
    ruleId: 'auto-01',
    ruleName: 'Boas-vindas Instantânea para Novos Leads do WhatsApp',
    contactName: 'Dr. Roberto Silveira',
    status: 'SUCCESS',
    reason: 'Corretor Lucas Brandão atribuído por rodízio + Tarefa criada com SLA de 15m.',
    executedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'log-02',
    tenantId: 'tenant-vanguard-01',
    ruleId: 'auto-02',
    ruleName: 'Lead Quente de Alta Renda -> Atribuição Gestor Sênior',
    contactName: 'Fernanda Castanheira',
    status: 'SUCCESS',
    reason: 'Tag #Cliente-VIP adicionada + Gestor Camila Mendonça notificada.',
    executedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'log-03',
    tenantId: 'tenant-vanguard-01',
    ruleId: 'auto-01',
    ruleName: 'Boas-vindas Instantânea para Novos Leads do WhatsApp',
    contactName: 'Carlos Eduardo Nogueira',
    status: 'SUCCESS',
    reason: 'Regra executada com sucesso para origem PORTAL_ZAP.',
    executedAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  }
];

